routes/web.php
//    return $service->getContactTags(3);
//    return $service->getContactByEmail('david@marketingprollc.com');
//    dd($service->getToken());
//    var_dump($service->requestAccessToken('pGtpFp0X'));
//    dd($service->refreshAccessToken());
//});
//Route::resource('test', 'TestController');

Route::get('legal', 'PageController@legal')->name('page.legal');

Route::get('countries/{country}/states', 'CountryController@getStates')->middleware('cors');
Route::get('deals/{property}/pdf/download', 'DealController@downloadPdf')->name('deals.download.pdf');
Route::get('property/{property}/pdf/download', 'DealController@downloadPropertyInfoPdf')->name('property.download.pdf');
Route::get('property/{property}/view-pdf', 'DealController@viewPdf');
//Rehab
Route::get('rehab/{property}/pdf/download', 'CostCalculatorController@downloadRehabPdf')->name('rehab.download.pdf');
Route::get('rehab/{template}/view-pdf', 'CostCalculatorController@viewRehabPdf');
Route::get('/housing-alert', function() {
    return view('integrations.housing-alert');
});

/**
 * Authenticated routes
 */
Route::group(['middleware' => 'auth'], function () {
    Route::post('upload-image', 'ContactController@uploadImage')->name('image.upload');
    Route::get('google-api-login', 'GcalendarController@googleLogin')->name('google.login');
    Route::get('sync-events', 'GcalendarController@create')->name('sync-gcalendar.create');

    Route::post('/save-tempalte', [
        'uses'=>'ContactController@saveTemplate',
        'as'=>'saveTemplate'
    ]);

    Route::get('/copy-template/{id}', [
        'uses'=>'CopyTemplateController@copyTemplate',
        'as'=>'copyTemplate'
    ]);
    Route::resource('manage-templates', 'TemplateController');

    Route::resource('my-team', 'MyTeamController');

    Route::get('print-genie-login', 'PrintGenieLoginController@index')->name('print-genie-login.index');

    Route::get('crei-ms-login', 'CreimsLoginController@index')->name('crei-ms-login.index');

    Route::get('creims-create-user', 'CreateCreiUsersController@create')->name('creims.create');

    Route::get('search', 'SearchController@index')->name('search');

    // Settings...
    Route::get('settings', 'SettingController@index')->name('settings.index');
    Route::post('settings/{group}', 'SettingController@store')->name('settings.store');

    // Subscription...
    Route::get('settings/billing', 'SettingController@billing')->name('settings.billing');
//	Route::get('settings/card', 'SettingController@getCard')->name('settings.card');
    Route::post('settings/card', 'SettingController@postCard')->name('settings.card');
//	Route::get('settings/subscription', 'SettingController@getSubscription')->name('settings.subscription');
    Route::post('settings/subscription', 'SettingController@postSubscription')->name('settings.subscription');
//	Route::get('settings/payments', 'SettingController@getPayments')->name('settings.payments');
    Route::get('settings/invoice/{invoice}', 'SettingController@downloadInvoice')->name('settings.invoice.download');
//	Route::get('settings/subscription/cancel', 'SettingController@getSubscriptionCancel')->name('settings.subscription.cancel');
    Route::post('settings/subscription/cancel', 'SettingController@postSubscriptionCancel')->name('settings.subscription.cancel');

    /**
     * Common routes
     */
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('onboarding', 'DashboardController@onboarding')->name('dashboard.onboarding');

    // Profile...
    Route::get('profile', 'ProfileController@getProfile')->name('profile');
    Route::post('profile', 'ProfileController@postProfile')->name('profile');
    Route::post('profile/picture', 'ProfileController@profilePicture')->name('profile.picture');
    Route::post('profile/password', 'ProfileController@updatePassword')->name('profile.password');

    // Integration...
    Route::get('integrations', 'IntegrationController@index')->name('integrations');
    // Activities...
    Route::get('activities', 'ActivityController@index')->name('activities');

    // DBM Integration
    Route::get('login/dbm', 'DBMController@index')->name('login.dbm');

    // user, super-user, admin routes...
    Route::group(['middleware' => ['role:user|super-user|admin|bird-dog-deal-finder']], function () {

        // Deals...
        Route::get('deals/upload', 'DealController@getUpload')->name('deals.upload');
        Route::post('deals/upload', 'DealController@postUpload')->name('deals.upload');
        Route::get('deals/watchlist', 'DealController@watchlist')->name('deals.watchlist');

        Route::get('deals', 'DealController@index')->name('deals.index');
        Route::get('deals/export', 'DealController@export')->name('deals.export');
        Route::get('deals/pending-properties', 'DealController@pendingProperties')->name('deals.pending-properties');
        Route::get('deals/create', 'DealController@create')->name('deals.create');
        Route::post('deals', 'DealController@store')->name('deals.store');
        Route::get('deals/{property}/edit', 'DealController@edit')->name('deals.edit');
        Route::get('deals/{property}', 'DealController@show')->name('deals.show');
        Route::put('deals/{property}', 'DealController@update')->name('deals.update');
        Route::get('deals/{property}/pdf', 'DealController@showPdf')->name('deals.show.pdf');
        Route::post('deals/{property}/email', 'DealController@sendEmail')->name('deals.email');
        Route::post('deals/{property}/transfer', 'DealController@transferDeal')->name('deals.transfer');
        Route::post('deals/{property}/user-transfer', 'DealController@transferUserDeal')->name('deals.user-transfer');
        Route::get('deals/{deal}/delete', 'DealController@destroy')->name('deals.delete');
        Route::get('user/{user}/deals', 'DealController@userDeals')->name('user.deals');
        Route::get('deals/blacklist/toggle/{property}', 'BlacklistController@dealToggle')->name('deals.blacklist.toggle');
        Route::get('deals/{property}/contract', 'DealController@showContract')->name('deals.show.contract');
        Route::post('deals/{property}/seller-locator-request', 'DealController@sendSellerLocatorRequest')->name('deals.seller-locator-request');
        Route::get('deals/{property}/proof-of-funds-request', 'DealController@sendProofOfFundsRequest')->name('deals.proof-of-funds-request');
        Route::get('deals/{property}/deal-funding-request', 'DealController@sendDealFundingRequest')->name('deals.deal-funding-request');
        Route::get('deals/{property}/contract/download', 'DealController@downloadContract')->name('deals.download.contract');

        // Contacts...
        Route::get('contacts/upload', 'ContactController@getUpload')->name('contacts.upload');
        Route::post('contacts/upload', 'ContactController@postUpload')->name('contacts.upload');
        Route::post('categories/file-upload', 'ContactController@fileUpload')->name('contacts.upload-ajax');
        Route::post('contacts/transfer', 'ContactController@transferContact')->name('contacts.transfer');
        Route::resource('contacts', 'ContactController', ['parameters' => 'singular']);
        Route::get('contacts/{contact}/delete', 'ContactController@destroy')->name('contacts.delete');
        Route::post('contacts/email', 'ContactController@sendEmail')->name('contacts.email');
        Route::post('contacts/message', 'ContactController@sendMessage')->name('contacts.message');
        Route::delete('contactsDeleteAll', 'ContactController@deleteAll')->name('delete-all-contacts');

        //Categories
        Route::get('categories/{category}/delete', 'ContactCategoryController@destroy')->name('categories.delete');
        Route::resource('categories', 'ContactCategoryController');


        // Contact groups...
        Route::resource('contact-groups', 'ContactGroupController', ['parameters' => 'singular']);
        Route::get('contact-groups/{contactGroup}/delete', 'ContactGroupController@destroy')->name('contact-groups.delete');
        Route::get('contact-groups/{contactGroup}/edit-members', 'ContactGroupController@editMembers')->name('contact-groups.edit-members');
        Route::put('contact-groups/{contactGroup}/update-members', 'ContactGroupController@updateMembers')->name('contact-groups.update-members');

        // Documents...
        Route::get('documents', 'DocumentController@index')->name('documents.index');
        Route::get('documents/create', 'DocumentController@create')->name('documents.create');
        Route::post('documents', 'DocumentController@store')->name('documents.store');
        Route::get('documents/{document}/edit', 'DocumentController@edit')->name('documents.edit');
        Route::put('documents/{document}', 'DocumentController@update')->name('documents.update');
        Route::get('documents/{document}/delete', 'DocumentController@destroy')->name('documents.delete');

        // Settings...
        Route::get('settings/emails', 'SettingController@getEmails')->name('settings.emails');
        Route::get('settings/message/templates', 'SettingController@getMessageTemplates')->name('settings.message-templates');

        // Calendar...
        Route::get('calendar', 'CalendarController@index')->name('calendar.index');
        Route::apiResource('events', 'EventController');

        // Resources...
        Route::get('resources/training', 'ResourceController@getTraining')->name('resources.training');
        Route::get('resources/faq', 'ResourceController@getFaq')->name('resources.faq');
        Route::get('resources/support', 'ResourceController@getSupport')->name('resources.support');

        Route::resource('broadcasts', 'BroadcastController');

        //DMP repair cost calculator
        Route::get('repair-cost-calculator/create/{property_id?}', 'CostCalculatorController@create')->name('calculator.template.create');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Spatie\Activitylog\Traits\LogsActivity;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contact extends Model
{
	use LogsActivity, SoftDeletes, Notifiable;
	
	protected $fillable = [
		'category_id', 'first_name', 'last_name', 'email_address', 'phone', 'alternate_phone', 'site_address', 'site_city', 'site_state',
        'site_zip_code', 'price_range_min', 'price_range_max', 'location',
        'mailing_city','site_zip_code', 'mailing_address', 'mailing_state', 'mailing_zip', 'site_county'
	];

    const DEFAULT_UPLOAD_CONTACTS_FIELDS = [
        'first_name',
        'last_name',
        'email_address',
        'phone',
        'alternate_phone',
        'site_address',
        'site_city',
        'site_state',
        'site_zip_code',
        'mailing_address',
        'mailing_state',
        'mailing_zip',
        'mailing_city',
        'site_county',
    ];

	protected static $recordEvents = ['updated', 'deleted'];

	public function user()
	{
		return $this->belongsTo(User::class);
	}

	public function category()
	{
		return $this->belongsTo(ContactCategory::class);
	}

	public function getFullNameAttribute()
	{
		return $this->last_name ? sprintf("%s %s", $this->first_name, $this->last_name) : $this->first_name;
	}

    public function contact_groups()
    {
        return $this->belongsToMany(ContactGroup::class);
	}

    public function routeNotificationForTwilio()
    {
        return $this->phone;
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class DashboardController extends Controller
{
	public function index()
	{
	    $user = auth()->user();

		if ($user && is_null($user->last_login)) {
			return redirect()->route('dashboard.onboarding');
		}

		if ($user->hasRole('super-user')) {
            return view('dashboard.team');
        }

        if ($user->hasRole('coach')) {
            return view('dashboard.coach');
        }

        return view('dashboard.index', compact('user'));
    }

	public function onboarding()
	{
		if (auth()->check() && is_null(auth()->user()->last_login)) {
			auth()->user()->setLastLoginTime();
		}

		return view('dashboard.onboarding');
	}
}

resources/views/dashboard/_finder_dashboard.blade.php
<div class="row match-height">

    <div class="col-xl-4 col-lg-6 col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-block">
                    <p class="card-text">
                    <div class="my-1 text-xs-center">
                        <div class="card-header mb-0 m-b-0 pt-0">
                            <h5 class="primary">INVESTOR PARTNERS</h5>
                            <span class="card-text font-small-1">Number of investors you are submitting deals for</span>
                            <h3 class="font-large-2 text-bold-200">{{ $dashboard->totalInvestorPartners() }}</h3>
                        </div>

                    </div>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-block">
                    <p class="card-text">
                    <div class="my-1 text-xs-center">
                        <div class="card-header mb-0 m-b-0 pt-0">
                            <h5 class="primary">TOTAL DEALS SENT</h5>
                            <span class="card-text font-small-1">Property leads you've submitted</span>
                            <h3 class="font-large-2 text-bold-200">{{ $dashboard->finderDealsCount() }}</h3>
                        </div>

                    </div>
                    </p>
                </div>

            </div>
        </div>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-block">
                    <p class="card-text">
                    <div class="my-1 text-xs-center">
                        <div class="card-header mb-0 m-b-0 pt-0">
                            <h5 class="primary">TOTAL DEALS CLOSED</h5>
                            <span class="card-text font-small-1">Property leads that have been purchased</span>
                            <h3 class="font-large-2 text-bold-200">{{ $dashboard->finderClosedDealsCount() }}</h3>
                        </div>

                    </div>
                    </p>
                </div>

            </div>
        </div>
    </div>

</div>
<div class="row match-height">
    <div class="col-xl-4 col-lg-6 col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-block">
                    <h4 class="card-title">Investor Partners</h4>
                    <p class="card-text">The following are the investors you have partnered up with to submit deals. The deals you've submited for these investors will be listed to the right.</p>

                    @foreach($dashboard->investorPartners() as $partner)
                        <div class="col-md-3 m-t-20">
                            <img src="{{ $partner->photoURL() }}" alt="{{ $partner->first_name }}" class="avatar-lrg avatar user-img">
                        </div>
                        <div class="col-md-9 m-t-20">
                            <span class="user-name">
                                <h5>{{ $partner->first_name }} <span class="font-small-1 tag tag-default tag-pill tag-success"><a href="{{ route('integration.deals.create', ['api_key' => $partner->api_key, 'finder_key' => $dashboard->user->api_key]) }}" target="_blank"> Add New Deal <i class="fa fa-external-link"> </i> </a></span></h5>
                            </span>

                            <div class="clearfix"></div>
                            @if($partner->state && $partner->country)
                            <p class="font-small-2 m-t-0">Currently based in {{ $partner->city }}, {{ $partner->state }}.</p>
                            @endif
                            <div class="clearfix"></div>
                            
                        </div>
                        
                    
                    @endforeach
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-8">
        <div class="card">
            <div class="card-body">
                <div class="card-block">
                    <h4 class="card-title">Current Deal Status</h4>
                </div>

                <div id="goal-list-scroll card-block" class="table-responsive height-250 position-relative">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Address</th>
                            <th>City</th>
                            <th>BR/BA</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($dashboard->finderDeals() as $deal)
                            <tr>
                                <td>{{ $deal->address }}</td>
                                <td>{{ $deal->city }}</td>
                                <td></td>
                                <td>{{ $deal->status }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row match-height">
    <div class="col-xl-4 col-lg-6 col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-block">
                    <h4 class="card-title">Deal Finder Training</h4>

                    <p class="card-text">The best skill you can have is finding great deals for your Investor Partners. The videos below will help get you on the right track.
                    </p>

                </div>

            </div>
        </div>
    </div>

    <div class="col-xs-8">
        <div class="card">
            <div class="card-body">
                <div class="card-block">
                    <h4 class="card-title">Documents</h4>

                    <p class="card-text">The following documents have been added to your account.
                    </p>

                </div>


            </div>
        </div>
    </div>
</div>

resources/views/dashboard/coach.blade.php
@extends('layouts.default')

@section('content')
	@inject('dashboard', 'App\Services\CoachDashboard')

	<div class="row match-height">
        <div class="col-xl-4 col-lg-6 col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-block">
                        <h4 class="card-title">Quick Links</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{{ route('dashboard.onboarding') }}">
                                <span class="tag tag-default tag-pill bg-warning float-xs-right">GO</span></a>
                                <strong> ONBOARDING TUTORIAL</strong>
                        </li>
                        <li class="list-group-item">
                            <a href="{{ route('deals.create') }}">
                                <span class="tag tag-default tag-pill bg-primary float-xs-right">GO</span></a>
                                <strong> ADD A NEW DEAL</strong>
                        </li>
                        <li class="list-group-item">
                            <a href="{{ route('deals.index') }}">
                                <span class="tag tag-default tag-pill bg-info float-xs-right">GO</span></a>
                                <strong> MANAGE EXISTING DEALS</strong>
                        </li>
                        <li class="list-group-item">
                            <a href="{{ route('contacts.create') }}">
                                <span class="tag tag-default tag-pill bg-danger float-xs-right">GO</span></a>
                                <strong>ADD A NEW CONTACT</strong>
                        </li>
                        <li class="list-group-item">
                            <a href="{{ route('resources.support') }}">
                                <span class="tag tag-default tag-pill bg-success float-xs-right">GO</span></a>
                                <strong>GET HELP FROM THE SUPPORT TEAM</strong>
                        </li>
                    </ul>
                    <div class="card-block">
                        <p class="card-text"><em>Quickly access commonly used links above</em></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-8">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-3 col-lg-6 col-md-12 border-right-blue-grey border-right-lighten-5">
                            @include('dashboard.partials.total_contacts')
                        </div>
                        <div class="col-xl-3 col-lg-6 col-md-12 border-right-blue-grey border-right-lighten-5">
                            @include('dashboard.partials.total_deals')
                        </div>
                        <div class="col-xl-3 col-lg-6 col-md-12 border-right-blue-grey border-right-lighten-5">
                            @include('dashboard.partials.total_closed_deals')
                        </div>
                        <div class="col-xl-3 col-lg-6 col-md-12 border-right-blue-grey border-right-lighten-5">
                            @include('dashboard.partials.total_wholesale_deals')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @role('coach')
    <div class="row match-height">
        <div class="col-xl-12 col-lg-6 col-md-12">
            <div class="card card-inverse card-success">
                <div class="card-body">

                    <div class="card-block p-b-0">
                        <h4 class="card-title">COACH ADMIN STATISTICS</h4>

                            <div class="row my-1 p-b-0">
                                <div class="col-lg-2 col-xs-12">
                                    <div class="text-xs-left card-text">
                                        <h3><span class="tag tag-default tag-pill bg-primary">{{ $dashboard->totalContactsAll() }}</span></h3>
                                        <p class="text-muted-light">Total Contacts</p>
                                        <div id="sp-tristate-bar-total-revenue"></div>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-xs-12 card-text">
                                    <div class="text-xs-left ">
                                        <h3><span class="tag tag-default tag-pill bg-primary">{{ $dashboard->totalCashBuyersAll() }}</span></h3>
                                        <p class="text-muted-light">Total Cash Buyers <span class="danger"></span></p>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-xs-12 card-text">
                                    <div class="text-xs-left">
                                        <h3><span class="tag tag-default tag-pill bg-primary">{{ $dashboard->totalUsers }}</span></h3>
                                        <p class="text-muted-light">Total Team Members</p>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-xs-12 card-text">
                                    <div class="text-xs-left">
                                        <h3><span class="tag tag-default tag-pill bg-primary">{{ $dashboard->totalNewDealsAll() }}</span></h3>
                                        <p class="text-muted-light">Total Open Deals* </p>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-xs-12 card-text">
                                    <div class="text-xs-left">
                                        <h3><span class="tag tag-default tag-pill bg-primary">{{ $dashboard->totalClosedDealsAll() }}</span></h3>
                                        <p class="text-muted-light">Total Closed Deals </p>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-xs-12 card-text">
                                    <div class="text-xs-left">
                                        <h3>
                                            <span class="tag tag-default tag-pill bg-primary">
                                                {{ formatPrice($dashboard->totalWholeSaleFeesCollectedAll()) }}
                                            </span>
                                        </h3>
                                        <p class="text-muted-light">Wholesale Income</p>
                                    </div>
                                </div>
                            </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
    @endrole
    
    <div class="row match-height">
        <div class="col-xl-8 col-xs-12">
            <div class="card">
                <div class="card-header no-border">
                    <h4 class="card-title">Recent Contacts</h4>
                    <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <div id="goal-list-scroll" class="table-responsive height-250 position-relative">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Category</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($dashboard->latestContacts as $contact)
                                <tr>
                                    <td>{{ $contact->full_name }}</td>
                                    <td>{{ $contact->email }}</td>
                                    <td>{{ $contact->mobile_phone }}</td>
                                    <td>{{ $contact->category->name }}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card">
                <div class="card-header no-border">
                    <h4 class="card-title">Information Card</h4>
                    <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">

                </div>
            </div>
        </div>

    </div>

    <div class="row">
        @include('dashboard.partials.latest_deals')
    </div>
@endsection

@section('scripts')	
	<script src="/app-assets/vendors/js/extensions/jquery.knob.min.js" type="text/javascript"></script>
    <script src="/app-assets/js/scripts/extensions/knob.js" type="text/javascript"></script>
@endsection