routes/web.php
<?php

use App\Services\Infusionsoft\Infusionsoft;

// Authentication Routes
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes
//Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('/register', 'Auth\RegisterController@register');

// Password Reset Routes
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset');

//Route::get('test', function() {

//    $event = \App\Event::latest()->first();
//    $event->user->notify(new \App\Notifications\EventReminder($event));

//    $contact = \App\Contact::latest()->first();
//    $user = $contact->user->setTwilioCredentials();

//    return $contact->notify(new \App\Notifications\SMSNotification('this is test'));
//    $service = new App\Services\Infusionsoft\Infusionsoft();

//    return $service->updateContactPassword('davidcorbaley@gmail.com', '1234');
//    dd(cache('infusionsoft.expires_in'));
//    dd($service->contactHasTag('davidcorbaley@gmail.com', 'M-CDP-ACCESS'));
//    dd($service->contactHasTag('david@marketingprollc.com', 'M-CDP-ACCESS'));
//    return $service->getContactTagsByEmail('david@marketingprollc.com');
//    return $service->getContactTags(3);
//    return $service->getContactByEmail('david@marketingprollc.com');
//    dd($service->getToken());
//    var_dump($service->requestAccessToken('pGtpFp0X'));
//    dd($service->refreshAccessToken());
//});
//Route::resource('test', 'TestController');

Route::get('legal', 'PageController@legal')->name('page.legal');

Route::get('countries/{country}/states', 'CountryController@getStates')->middleware('cors');
Route::get('deals/{property}/pdf/download', 'DealController@downloadPdf')->name('deals.download.pdf');
Route::get('property/{property}/pdf/download', 'DealController@downloadPropertyInfoPdf')->name('property.download.pdf');
Route::get('property/{property}/view-pdf', 'DealController@viewPdf');
//Rehab
Route::get('rehab/{property}/pdf/download', 'CostCalculatorController@downloadRehabPdf')->name('rehab.download.pdf');
Route::get('rehab/{template}/view-pdf', 'CostCalculatorController@viewRehabPdf');
Route::get('/housing-alert', function() {
    return view('integrations.housing-alert');
});

/**
 * Authenticated routes
 */
Route::group(['middleware' => 'auth'], function () {
    Route::post('upload-image', 'ContactController@uploadImage')->name('image.upload');
    Route::get('google-api-login', 'GcalendarController@googleLogin')->name('google.login');
    Route::get('sync-events', 'GcalendarController@create')->name('sync-gcalendar.create');

    Route::post('/save-tempalte', [
        'uses'=>'ContactController@saveTemplate',
        'as'=>'saveTemplate'
    ]);

    Route::get('/copy-template/{id}', [
        'uses'=>'CopyTemplateController@copyTemplate',
        'as'=>'copyTemplate'
    ]);
    Route::resource('manage-templates', 'TemplateController');

    Route::resource('my-team', 'MyTeamController');

    Route::get('print-genie-login', 'PrintGenieLoginController@index')->name('print-genie-login.index');

    Route::get('crei-ms-login', 'CreimsLoginController@index')->name('crei-ms-login.index');

    Route::get('creims-create-user', 'CreateCreiUsersController@create')->name('creims.create');

    Route::get('search', 'SearchController@index')->name('search');

    // Settings...
    Route::get('settings', 'SettingController@index')->name('settings.index');
    Route::post('settings/{group}', 'SettingController@store')->name('settings.store');

    // Subscription...
    Route::get('settings/billing', 'SettingController@billing')->name('settings.billing');
//	Route::get('settings/card', 'SettingController@getCard')->name('settings.card');
    Route::post('settings/card', 'SettingController@postCard')->name('settings.card');
//	Route::get('settings/subscription', 'SettingController@getSubscription')->name('settings.subscription');
    Route::post('settings/subscription', 'SettingController@postSubscription')->name('settings.subscription');
//	Route::get('settings/payments', 'SettingController@getPayments')->name('settings.payments');
    Route::get('settings/invoice/{invoice}', 'SettingController@downloadInvoice')->name('settings.invoice.download');
//	Route::get('settings/subscription/cancel', 'SettingController@getSubscriptionCancel')->name('settings.subscription.cancel');
    Route::post('settings/subscription/cancel', 'SettingController@postSubscriptionCancel')->name('settings.subscription.cancel');

    /**
     * Common routes
     */
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('onboarding', 'DashboardController@onboarding')->name('dashboard.onboarding');

    // Profile...
    Route::get('profile', 'ProfileController@getProfile')->name('profile');
    Route::post('profile', 'ProfileController@postProfile')->name('profile');
    Route::post('profile/picture', 'ProfileController@profilePicture')->name('profile.picture');
    Route::post('profile/password', 'ProfileController@updatePassword')->name('profile.password');

    // Integration...
    Route::get('integrations', 'IntegrationController@index')->name('integrations');
    // Activities...
    Route::get('activities', 'ActivityController@index')->name('activities');

    // DBM Integration
    Route::get('login/dbm', 'DBMController@index')->name('login.dbm');

    // user, super-user, admin routes...
    Route::group(['middleware' => ['role:user|super-user|admin|bird-dog-deal-finder']], function () {

        // Deals...
        Route::get('deals/upload', 'DealController@getUpload')->name('deals.upload');
        Route::post('deals/upload', 'DealController@postUpload')->name('deals.upload');
        Route::get('deals/watchlist', 'DealController@watchlist')->name('deals.watchlist');

        Route::get('deals', 'DealController@index')->name('deals.index');
        Route::get('deals/export', 'DealController@export')->name('deals.export');
        Route::get('deals/pending-properties', 'DealController@pendingProperties')->name('deals.pending-properties');
        Route::get('deals/create', 'DealController@create')->name('deals.create');
        Route::post('deals', 'DealController@store')->name('deals.store');
        Route::get('deals/{property}/edit', 'DealController@edit')->name('deals.edit');
        Route::get('deals/{property}', 'DealController@show')->name('deals.show');
        Route::put('deals/{property}', 'DealController@update')->name('deals.update');
        Route::get('deals/{property}/pdf', 'DealController@showPdf')->name('deals.show.pdf');
        Route::post('deals/{property}/email', 'DealController@sendEmail')->name('deals.email');
        Route::post('deals/{property}/transfer', 'DealController@transferDeal')->name('deals.transfer');
        Route::post('deals/{property}/user-transfer', 'DealController@transferUserDeal')->name('deals.user-transfer');
        Route::get('deals/{deal}/delete', 'DealController@destroy')->name('deals.delete');
        Route::get('user/{user}/deals', 'DealController@userDeals')->name('user.deals');
        Route::get('deals/blacklist/toggle/{property}', 'BlacklistController@dealToggle')->name('deals.blacklist.toggle');
        Route::get('deals/{property}/contract', 'DealController@showContract')->name('deals.show.contract');
        Route::post('deals/{property}/seller-locator-request', 'DealController@sendSellerLocatorRequest')->name('deals.seller-locator-request');
        Route::get('deals/{property}/proof-of-funds-request', 'DealController@sendProofOfFundsRequest')->name('deals.proof-of-funds-request');
        Route::get('deals/{property}/deal-funding-request', 'DealController@sendDealFundingRequest')->name('deals.deal-funding-request');
        Route::get('deals/{property}/contract/download', 'DealController@downloadContract')->name('deals.download.contract');

        // Contacts...
        Route::get('contacts/upload', 'ContactController@getUpload')->name('contacts.upload');
        Route::post('contacts/upload', 'ContactController@postUpload')->name('contacts.upload');
        Route::post('categories/file-upload', 'ContactController@fileUpload')->name('contacts.upload-ajax');
        Route::post('contacts/transfer', 'ContactController@transferContact')->name('contacts.transfer');
        Route::resource('contacts', 'ContactController', ['parameters' => 'singular']);
        Route::get('contacts/{contact}/delete', 'ContactController@destroy')->name('contacts.delete');
        Route::post('contacts/email', 'ContactController@sendEmail')->name('contacts.email');
        Route::post('contacts/message', 'ContactController@sendMessage')->name('contacts.message');
        Route::delete('contactsDeleteAll', 'ContactController@deleteAll')->name('delete-all-contacts');

        //Categories
        Route::get('categories/{category}/delete', 'ContactCategoryController@destroy')->name('categories.delete');
        Route::resource('categories', 'ContactCategoryController');


        // Contact groups...
        Route::resource('contact-groups', 'ContactGroupController', ['parameters' => 'singular']);
        Route::get('contact-groups/{contactGroup}/delete', 'ContactGroupController@destroy')->name('contact-groups.delete');
        Route::get('contact-groups/{contactGroup}/edit-members', 'ContactGroupController@editMembers')->name('contact-groups.edit-members');

resources/views/templates/_form.blade.php
<div class="card-box">
	<h5 class="m-t-0 m-t-20 subtitle-text">TEMPLATE INFORMATION</h5>

	<div class="row">
		<!--- Name Field --->
		<div class="form-group input-group-sm col-sm-4">
			{!! Form::label('name', 'Name:') !!} <span class="red">*</span>
			{!! Form::text('name', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<!-- <div class="row"> -->
		<!--- Subject Field --->
		<!-- <div class="form-group input-group-sm col-sm-4"> -->
			<!-- {!! Form::label('subject', 'Subject:') !!} <span class="red">*</span> -->
			<!-- {!! Form::text('subject', null, ['class' => 'form-control']) !!} -->
		<!-- </div> -->
	<!-- </div> -->

	<div class="row">
		<!--- Message Field --->
		<div class="form-group input-group-sm col-sm-8">
			{!! Form::label('message', 'Message:') !!} <span class="red">*</span>
			{!! Form::textarea('message', null, ['class' => 'form-control', 'id' => 'message']) !!}
		</div>
	</div>

	<!--- Save Changes Field --->
	<div class="form-group input-group-sm input-group-sm m-t-30 text-right">
		{!! Form::submit($submitButtonText, ['class' => 'btn btn-success']) !!}
		<button type="button" onclick="goBack()" class="btn btn-default">Cancel</button>
	</div>
</div>

resources/views/templates/create.blade.php
@extends('layouts.default')

@section('content')

    <!-- Page-Title -->
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Create Template</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a>
                  </li>
                    <li class="breadcrumb-item"><a href="{{ route('manage-templates.index') }}">Templates</a>
                  </li>
                  <li class="breadcrumb-item active">Create Template</li>
                </ol>
              </div>
                <div class="col-xs-12">@include('partials.errors')</div>
            </div>
         </div>
    </div>

    <div class="content-detached">
        <div class="content-body">

            <!-- Main Content Area -->
            <section id="description" class="card">
                <div class="card-header">
                    <h4 class="card-title">Add New Template</h4>
                    <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                        </ul>
                    </div>
                </div>
                {!! Form::open(['route' => 'manage-templates.store']) !!}
                <div class="card-body collapse in">
                    <div class="card-block">
                        <div class="card-text">
                            @include('templates._form', ['submitButtonText' => 'Save'])
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </section>
            <!--/ Main Content Area -->

        </div>
    </div>

@endsection
@section('scripts')
	<script src="https://cdn.ckeditor.com/ckeditor5/23.0.0/classic/ckeditor.js"></script>
    <script>
        class MyUploadAdapter {
        constructor( loader ) {
            // CKEditor 5's FileLoader instance.
            this.loader = loader;

            // URL where to send files.
            this.url = '{{route("image.upload")}}';
        }

        // Starts the upload process.
        upload() {
            return this.loader.file
                .then( file => new Promise( ( resolve, reject ) => {
                    this._initRequest();
                    this._initListeners( resolve, reject, file );
                    this._sendRequest( file );
                } ) );
        }

        // Aborts the upload process.
        abort() {
            if ( this.xhr ) {
                this.xhr.abort();
            }
        }


        _initRequest() {
            const xhr = this.xhr = new XMLHttpRequest();

            xhr.open( 'POST', this.url ,true);
            xhr.responseType = 'json';
        }


        _initListeners( resolve, reject,file ) {
            const xhr = this.xhr;
            const loader = this.loader;
            const genericErrorText = 'Couldn\'t upload file:' + ` ${ file.name }.`;

            xhr.addEventListener( 'error', () => reject( genericErrorText ) );
            xhr.addEventListener( 'abort', () => reject() );
            xhr.addEventListener( 'load', () => {
                const response = xhr.response;

                if ( !response || response.error ) {
                    return reject( response && response.error ? response.error.message : genericErrorText );
                }
                //console.log(response);
                // If the upload is successful, resolve the upload promise with an object containing
                // at least the "default" URL, pointing to the image on the server.
                resolve( {
                    default: response.url
                } );
            } );

            if ( xhr.upload ) {
                xhr.upload.addEventListener( 'progress', evt => {
                    if ( evt.lengthComputable ) {
                        loader.uploadTotal = evt.total;
                        loader.uploaded = evt.loaded;
                    }
                } );
            }
        }

        // Prepares the data and sends the request.
        _sendRequest(file) {
            const data = new FormData();
            //console.log(this.loader.file);
            data.append('upload', file );
        //csrf_token CSRF protection
            //data.append('csrf_token', requestToken);

            this.xhr.send( data );
        }
    }
    function MyCustomUploadAdapterPlugin( editor ) {
        editor.plugins.get( 'FileRepository' ).createUploadAdapter = ( loader ) => {
            return new MyUploadAdapter( loader );
        };
    }

    function init_ckeditor(selector,timeout){
        ClassicEditor
            .create( document.querySelector(selector ),{
                extraPlugins: [ MyCustomUploadAdapterPlugin ],
            } )
            .then( editor => {
                console.log( editor );
            } )
            .catch( error => {
                console.error( error );
            } );
    }   

    init_ckeditor('#message' );
		// ClassicEditor
        //     .create( document.querySelector( '#message' ), {
        //         ckfinder: {
        //             uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'
        //         },
		// 		removePlugins: [ 'Blockquote' ],
        //         // plugins: [ ... , ImageInsert ],
		// 		// toolbar: [
		// 		// 	'Image',
		// 		// 	'bold',
		// 		// 	'italic',
		// 		// 	'link',
		// 		// 	'unlink'
		// 		// ]
		// 	})
        //     .catch( error => {
        //         console.error( error );
        //     } );
    </script>
@endsection

resources/views/templates/edit.blade.php
@extends('layouts.default')

@section('content')

<!-- Page-Title -->
 <div class="content-header row">
	<div class="content-header-left col-md-6 col-xs-12 mb-2">
		<h3 class="content-header-title mb-0">Edit Template</h3>
		<div class="row breadcrumbs-top">
		  <div class="breadcrumb-wrapper col-xs-12">
			<ol class="breadcrumb">
			  <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a>
			  </li>
				<li class="breadcrumb-item"><a href="{{ route('manage-templates.index') }}">Templates</a>
			  </li>
			  <li class="breadcrumb-item active">Edit Template</li>
			</ol>
		  </div>
			<div class="col-xs-12">@include('partials.errors')</div>
		</div>
	 </div>
</div>

<div class="content-detached">
	<div class="content-body">
		<!-- Main Content Area -->
		<section id="description" class="card">
			<div class="card-header">
				<h4 class="card-title">Edit Template</h4>
				<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
				<div class="heading-elements">
					<ul class="list-inline mb-0">
						<li><a data-action="collapse"><i class="ft-minus"></i></a></li>
						<li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
						<li><a data-action="expand"><i class="ft-maximize"></i></a></li>
					</ul>
				</div>
			</div>
			{!! Form::model($template, ['route' => ['manage-templates.update', $template->id], 'method' => 'PUT']) !!}
			<div class="card-body collapse in">
				<div class="card-block">
					<div class="card-text">
					   @include('templates._form', ['submitButtonText' => 'Update'])
					</div>
				</div>
			</div>
			{!! Form::close() !!}
		</section>
		<!--/ Main Content Area -->
	</div>
</div>
@endsection
@section('scripts')
	<script src="https://cdn.ckeditor.com/ckeditor5/23.0.0/classic/ckeditor.js"></script>
    <script>
        class MyUploadAdapter {
        constructor( loader ) {
            // CKEditor 5's FileLoader instance.
            this.loader = loader;

            // URL where to send files.
            this.url = '{{route("image.upload")}}';
        }

        // Starts the upload process.
        upload() {
            return this.loader.file
                .then( file => new Promise( ( resolve, reject ) => {
                    this._initRequest();
                    this._initListeners( resolve, reject, file );
                    this._sendRequest( file );
                } ) );
        }

        // Aborts the upload process.
        abort() {
            if ( this.xhr ) {
                this.xhr.abort();
            }
        }


        _initRequest() {
            const xhr = this.xhr = new XMLHttpRequest();

            xhr.open( 'POST', this.url ,true);
            xhr.responseType = 'json';
        }


        _initListeners( resolve, reject,file ) {
            const xhr = this.xhr;
            const loader = this.loader;
            const genericErrorText = 'Couldn\'t upload file:' + ` ${ file.name }.`;

            xhr.addEventListener( 'error', () => reject( genericErrorText ) );
            xhr.addEventListener( 'abort', () => reject() );
            xhr.addEventListener( 'load', () => {
                const response = xhr.response;

                if ( !response || response.error ) {
                    return reject( response && response.error ? response.error.message : genericErrorText );
                }
                //console.log(response);
                // If the upload is successful, resolve the upload promise with an object containing
                // at least the "default" URL, pointing to the image on the server.
                resolve( {
                    default: response.url
                } );
            } );

            if ( xhr.upload ) {
                xhr.upload.addEventListener( 'progress', evt => {
                    if ( evt.lengthComputable ) {
                        loader.uploadTotal = evt.total;
                        loader.uploaded = evt.loaded;
                    }
                } );
            }
        }

        // Prepares the data and sends the request.
        _sendRequest(file) {
            const data = new FormData();
            //console.log(this.loader.file);
            data.append('upload', file );
        //csrf_token CSRF protection
            //data.append('csrf_token', requestToken);

            this.xhr.send( data );
        }
    }
    function MyCustomUploadAdapterPlugin( editor ) {
        editor.plugins.get( 'FileRepository' ).createUploadAdapter = ( loader ) => {
            return new MyUploadAdapter( loader );
        };
    }

    function init_ckeditor(selector,timeout){
        ClassicEditor
            .create( document.querySelector(selector ),{
                extraPlugins: [ MyCustomUploadAdapterPlugin ],
                removePlugins: [ 'Blockquote' ],
                toolbar: [
					'bold',
					'italic',
					'link',
					'unlink',
                    'ImageUpload'
				]
            } )
            .then( editor => {
                console.log( editor );
            } )
            .catch( error => {
                console.error( error );
            } );
    }   

    init_ckeditor('#message' );
    </script>
@endsection

resources/views/templates/index.blade.php
@extends('layouts.default')

@section('content')
<!-- Page-Title -->
<div class="content-header row">
    <div class="content-header-left col-md-6 col-xs-12 mb-2">
      <h3 class="content-header-title mb-0">Manage Templates</h3>
      <div class="row breadcrumbs-top">
        <div class="breadcrumb-wrapper col-xs-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('manage-templates.index') }}">Templates</a>
            </li>
            <li class="breadcrumb-item active">My Templates
            </li>
          </ol>
        </div>
      </div>
    </div>
    <div class="content-header-right col-md-6 col-xs-12">
      <div class="media width-250 float-xs-right">
        <div class="media-left media-middle">

        </div>
        <div class="media-body media-right text-xs-right">
          <div class="btn-group pull-right m-t-15 hidden-print">
						<!-- Add Contacts Button -->
						<a href="{{ route('manage-templates.create') }}" class="btn btn-success waves-effect waves-light m-r-5" data-toggle="tooltip" data-placement="left" title="" data-original-title="Add New Template"><span class=""><i class="fa fa-plus"></i></span></a>
					</div>
        </div>
      </div>
    </div>
</div>

<section id="mobile-support">
	<div class="row">
		<div class="col-xs-12">
			<div class="card">
				<div class="card-header">
					<div class="heading-elements">
						<ul class="list-inline mb-0">
							<li><a data-action="collapse"><i class="ft-minus"></i></a></li>
							<li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
							<li><a data-action="expand"><i class="ft-maximize"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="card-body collapse in">
					<div class="card-block card-dashboard">
						<p class="card-text">The following templates are in your database. You can use these message template list to send email contacts.</p>
						<table class="table table-striped table-bordered responsive dataex-rowre-mobilesupport">
							<thead>
								<tr>									
									<th>Template Name</th>									
									<th>Message</th>									
									<th>Created At</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@foreach($templates as $template)								
									<tr>
										<td>{{ $template->name ?? 'N/A' }}</td>
										<td>{!! nl2br(html_entity_decode(e($template->message))) !!}</td>										
										<td>{{ $template->created_at->format('M d, Y h:i a') }}</td>
										<td>
											<a href="{{ route('manage-templates.edit', $template->id) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit {{ $template->name }}'s Details"><i class="fa fa-pencil"></i></a>		

											<a href="{{ route('copyTemplate', $template->id) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="" data-original-title="Copy Template Row"><i class="fa fa-clone"></i></a>

											<a  class="btn btn-sm btn-danger"
											    href="{{ route('manage-templates.destroy', ['template' => $template]) }}"
											    onclick="if(confirm('Are you sure to delete this template?')){event.preventDefault();
											    document.getElementById('delete-form-{{ $template->id }}').submit();}">
											    <i class="fa fa-trash"></i>
											</a>
											{!! Form::open(['route' => ['manage-templates.destroy', $template->id], 'method' => 'DELETE', 'style' => 'display:none;', 'id' => "delete-form-".$template->id]) !!}
											
											    {{ csrf_field() }}    											
											{!! Form::close() !!}
										</td>
									</tr>
								@endforeach
							</tbody>
							<tfoot>
								<tr>
									<th>Template Name</th>									
									<th>Message</th>									
									<th>Created At</th>
									<th>Action</th>
								</tr>
							</tfoot>
						</table>				
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection